# Copyright (c) 2024 FRANC Service Portal
# All rights reserved.

"""Generated Infrahub schema protocols."""

#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreArtifactTarget,
    CoreNode,
    CoreObjectComponentTemplate,
    CoreObjectTemplate,
    CoreProfile,
    LineageSource,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        BooleanOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPNetwork,
        String,
        StringOptional,
    )


class TemplateCoreArtifactTarget(CoreNode):
    template_name: String
    artifacts: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimEndpoint(CoreNode):
    template_name: String
    connector: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimGenericDevice(CoreNode):
    description: StringOptional
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    template_name: String
    device_service: RelationshipManager
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    topology: RelatedNode


class TemplateDcimInterface(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    template_name: String
    device: RelatedNode
    member_of_groups: RelationshipManager
    service: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimSubInterface(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TopologyDeployment(CoreNode):
    description: StringOptional
    emulation: BooleanOptional
    name: String
    customer_subnet: RelatedNode
    design: RelatedNode
    devices: RelationshipManager
    fabric_services: RelationshipManager
    location: RelatedNode
    management_subnet: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimEndpoint(CoreNode):
    connector: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationGeneric(CoreNode):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    policy: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class OrganizationGeneric(CoreNode):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    namespaces: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceGeneric(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityGenericAddress(CoreNode):
    name: String
    address_groups: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityGenericAddressGroup(CoreNode):
    description: StringOptional
    name: String
    addresses: RelationshipManager
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimGenericDevice(CoreNode):
    description: StringOptional
    name: String
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    device_service: RelationshipManager
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    topology: RelatedNode


class DcimGenericSFP(CoreNode):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: DropdownOptional
    interface: RelatedNode
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    spare_location: RelatedNode
    subscriber_of_groups: RelationshipManager


class SecurityGenericService(CoreNode):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityGenericServiceGroup(CoreNode):
    description: StringOptional
    name: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    services: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationHosting(CoreNode):
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    prefixes: RelationshipManager
    profiles: RelationshipManager
    spare_sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimInterface(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class NetworkManagementServer(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown
    ip_addresses: RelationshipManager
    location: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityPolicyAssignment(CoreNode):
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    rules: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceRoutingPolicy(CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimSubInterface(CoreNode):
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager


class CoreWeightedPoolResource(CoreNode):
    allocation_weight: IntegerOptional
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityAddressGroup(SecurityGenericAddressGroup):
    description: StringOptional
    name: String
    addresses: RelationshipManager
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceAutonomousSystem(ServiceGeneric):
    asn: Integer
    description: StringOptional
    name: String
    status: Dropdown
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    provider: RelatedNode
    subscriber_of_groups: RelationshipManager


class ServiceBGPCommunity(CoreNode):
    community: String
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    routing_policy: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceBGPPeerGroup(ServiceGeneric):
    address_family: DropdownOptional
    description: StringOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    name: String
    send_community: BooleanOptional
    status: Dropdown
    export_routing_policies: RelationshipManager
    import_routing_policies: RelationshipManager
    local_as: RelatedNode
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    remote_as: RelatedNode
    subscriber_of_groups: RelationshipManager


class ServiceBGPSession(ServiceGeneric):
    description: StringOptional
    local_pref: IntegerOptional
    name: String
    role: Dropdown
    session_type: String
    status: Dropdown
    device: RelatedNode
    export_routing_policies: RelationshipManager
    import_routing_policies: RelationshipManager
    local_as: RelatedNode
    local_ip: RelatedNode
    member_of_groups: RelationshipManager
    owner: RelatedNode
    peer_group: RelatedNode
    peer_session: RelatedNode
    profiles: RelationshipManager
    remote_as: RelatedNode
    remote_ip: RelatedNode
    subscriber_of_groups: RelationshipManager


class DcimBidiSFP(DcimGenericSFP):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: DropdownOptional
    wavelength_rx: Integer
    wavelength_tx: Integer
    interface: RelatedNode
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    spare_location: RelatedNode
    subscriber_of_groups: RelationshipManager


class TopologyBranchOffice(CoreArtifactTarget, TopologyDeployment):
    description: StringOptional
    emulation: BooleanOptional
    name: String
    artifacts: RelationshipManager
    customer_subnet: RelatedNode
    design: RelatedNode
    devices: RelationshipManager
    fabric_services: RelationshipManager
    location: RelatedNode
    management_subnet: RelatedNode
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationBuilding(LocationGeneric, LocationHosting):
    description: StringOptional
    facility_id: StringOptional
    name: String
    physical_address: StringOptional
    shortname: String
    children: RelationshipManager
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    policy: RelatedNode
    prefixes: RelationshipManager
    profiles: RelationshipManager
    spare_sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TopologyColocationCenter(CoreArtifactTarget, TopologyDeployment):
    description: StringOptional
    emulation: BooleanOptional
    name: String
    artifacts: RelationshipManager
    asn: RelatedNode
    customer_subnet: RelatedNode
    design: RelatedNode
    devices: RelationshipManager
    fabric_services: RelationshipManager
    location: RelatedNode
    management_subnet: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimConsoleInterface(DcimInterface, DcimEndpoint, CoreArtifactTarget):
    description: StringOptional
    name: String
    port: IntegerOptional
    role: DropdownOptional
    speed: IntegerOptional
    status: DropdownOptional
    artifacts: RelationshipManager
    connector: RelatedNode
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationCountry(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    timezone: StringOptional
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    policy: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class OrganizationCustomer(OrganizationGeneric):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    namespaces: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TopologyDataCenter(CoreArtifactTarget, TopologyDeployment):
    description: StringOptional
    emulation: BooleanOptional
    name: String
    strategy: Dropdown
    artifacts: RelationshipManager
    customer_subnet: RelatedNode
    design: RelatedNode
    devices: RelationshipManager
    fabric_services: RelationshipManager
    location: RelatedNode
    management_subnet: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    provider: RelatedNode
    public_subnet: RelatedNode
    subscriber_of_groups: RelationshipManager
    technical_subnet: RelatedNode


class DcimDeviceType(CoreNode):
    description: StringOptional
    full_depth: BooleanOptional
    height: IntegerOptional
    name: String
    part_number: StringOptional
    weight: IntegerOptional
    design_components: RelationshipManager
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class NetworkDhcpOption(CoreNode):
    content: String
    description: StringOptional
    name: String
    option_code: Integer
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class NetworkDhcpServer(NetworkManagementServer):
    description: StringOptional
    lease_time: String
    name: String
    status: Dropdown
    dhcp_options: RelationshipManager
    ip_addresses: RelationshipManager
    location: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DesignElement(CoreNode):
    description: StringOptional
    name: String
    quantity: Integer
    role: DropdownOptional
    device_type: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    template: RelatedNode


class SecurityFQDN(SecurityGenericAddress):
    fqdn: String
    name: String
    address_groups: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationFloor(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    policy: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class IpamIPAddress(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    fqdn: StringOptional
    ip_namespace: RelatedNode
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityIPAddress(SecurityGenericAddress):
    address: IPHost
    description: StringOptional
    name: String
    address_groups: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityIPProtocol(SecurityGenericService):
    description: StringOptional
    name: String
    protocol: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityIPRange(SecurityGenericAddress):
    end: IPHost
    name: String
    start: IPHost
    address_groups: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityIpamIPAddress(SecurityGenericAddress):
    description: StringOptional
    name: String
    address_groups: RelationshipManager
    ip_address: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityIpamPrefix(SecurityGenericAddress):
    description: StringOptional
    name: String
    address_groups: RelationshipManager
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class OrganizationManufacturer(CoreNode):
    description: StringOptional
    name: String
    device_type: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelationshipManager
    profiles: RelationshipManager
    sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationMetro(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    policy: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class NetworkNTPServer(NetworkManagementServer):
    description: StringOptional
    name: String
    status: Dropdown
    ip_addresses: RelationshipManager
    location: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class NetworkNameServer(NetworkManagementServer):
    description: StringOptional
    name: String
    status: Dropdown
    ip_addresses: RelationshipManager
    location: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceNetworkSegment(ServiceGeneric):
    description: StringOptional
    name: String
    status: Dropdown
    vni: Integer
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    prefixes: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceOSPF(ServiceGeneric):
    description: StringOptional
    name: String
    reference_bandwidth: IntegerOptional
    status: Dropdown
    version: DropdownOptional
    area: RelatedNode
    device: RelatedNode
    export_routing_policies: RelationshipManager
    import_routing_policies: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    router_id: RelatedNode
    subscriber_of_groups: RelationshipManager


class ServiceOSPFArea(ServiceGeneric):
    area: Integer
    description: StringOptional
    name: String
    status: Dropdown
    member_of_groups: RelationshipManager
    namespace: RelatedNode
    ospf_interfaces: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceOSPFInterface(ServiceGeneric):
    authentication_key: StringOptional
    authentication_mode: DropdownOptional
    description: StringOptional
    metric: IntegerOptional
    mode: DropdownOptional
    name: String
    status: Dropdown
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    settings_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimPhysicalDevice(CoreArtifactTarget, DcimGenericDevice):
    description: StringOptional
    name: String
    os_version: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    status: Dropdown
    artifacts: RelationshipManager
    device_service: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    object_template: RelatedNode
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    topology: RelatedNode


class DcimPhysicalInterface(DcimInterface, DcimEndpoint, DcimSubInterface):
    description: StringOptional
    interface_type: DropdownOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    connector: RelatedNode
    device: RelatedNode
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    plugged_sfp: RelatedNode
    profiles: RelationshipManager
    service: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimPlatform(CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    name: String
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    devices: RelationshipManager
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityPolicy(CoreNode):
    description: StringOptional
    name: String
    location_target: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    rules: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityPolicyRule(CoreNode):
    action: StringOptional
    index: Integer
    log: BooleanOptional
    name: String
    destination_address: RelationshipManager
    destination_groups: RelationshipManager
    destination_service_groups: RelationshipManager
    destination_services: RelationshipManager
    destination_zone: RelatedNode
    member_of_groups: RelationshipManager
    policy: RelatedNode
    profiles: RelationshipManager
    source_address: RelationshipManager
    source_groups: RelationshipManager
    source_service_groups: RelationshipManager
    source_services: RelationshipManager
    source_zone: RelatedNode
    subscriber_of_groups: RelationshipManager


class IpamPrefix(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: BooleanOptional
    is_top_level: BooleanOptional
    member_type: DropdownOptional
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    role: DropdownOptional
    status: Dropdown
    utilization: IntegerOptional
    children: RelationshipManager
    gateway: RelatedNode
    ip_addresses: RelationshipManager
    ip_namespace: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    resource_pool: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityPrefix(SecurityGenericAddress):
    description: StringOptional
    name: String
    prefix: IPNetwork
    address_groups: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class OrganizationProvider(OrganizationGeneric):
    description: StringOptional
    name: String
    asns: RelationshipManager
    location: RelationshipManager
    member_of_groups: RelationshipManager
    namespaces: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationRack(LocationGeneric, LocationHosting):
    description: StringOptional
    facility_id: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    policy: RelatedNode
    prefixes: RelationshipManager
    profiles: RelationshipManager
    spare_sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationRegion(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    policy: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class SecurityRenderedPolicyRule(CoreNode):
    action: StringOptional
    index: Integer
    log: BooleanOptional
    name: String
    destination_address: RelationshipManager
    destination_groups: RelationshipManager
    destination_service_groups: RelationshipManager
    destination_services: RelationshipManager
    destination_zone: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    source_address: RelationshipManager
    source_groups: RelationshipManager
    source_policy: RelatedNode
    source_service_groups: RelationshipManager
    source_services: RelationshipManager
    source_zone: RelatedNode
    subscriber_of_groups: RelationshipManager


class ServiceRoutingPolicyBGP(ServiceRoutingPolicy):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceRoutingPolicyOSPF(ServiceRoutingPolicy):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityService(SecurityGenericService):
    description: StringOptional
    name: String
    port: Integer
    ip_protocol: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityServiceGroup(SecurityGenericServiceGroup):
    description: StringOptional
    name: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    services: RelationshipManager
    subscriber_of_groups: RelationshipManager


class SecurityServiceRange(SecurityGenericService):
    description: StringOptional
    end: Integer
    name: String
    start: Integer
    ip_protocol: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimStandardSFP(DcimGenericSFP):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: DropdownOptional
    interface: RelatedNode
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    spare_location: RelatedNode
    subscriber_of_groups: RelationshipManager


class LocationSuite(LocationGeneric):
    description: StringOptional
    facility_id: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    policy: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DesignTopology(CoreArtifactTarget):
    description: StringOptional
    name: String
    type: DropdownOptional
    artifacts: RelationshipManager
    elements: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimVirtualDevice(CoreArtifactTarget, DcimGenericDevice):
    description: StringOptional
    name: String
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    artifacts: RelationshipManager
    device_service: RelationshipManager
    hosting_device: RelatedNode
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    object_template: RelatedNode
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    topology: RelatedNode


class DcimVirtualInterface(DcimInterface):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    device: RelatedNode
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    parent_interface: RelatedNode
    profiles: RelationshipManager
    service: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class SecurityZone(CoreNode):
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinTag(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimBidiSFP(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    serial: StringOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimConsoleInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    port: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    speed: IntegerOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimDeviceType(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    full_depth: BooleanOptional
    height: IntegerOptional
    part_number: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimEndpoint(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimGenericDevice(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    os_version: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimGenericSFP(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    serial: StringOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPhysicalDevice(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    os_version: StringOptional
    position: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPhysicalInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    interface_type: DropdownOptional
    mtu: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPlatform(LineageSource, CoreProfile, CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimStandardSFP(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    serial: StringOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimSubInterface(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimVirtualDevice(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    os_version: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimVirtualInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDesignElement(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDesignTopology(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    type: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    fqdn: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamNamespace(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationBuilding(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    facility_id: StringOptional
    physical_address: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationCountry(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    timezone: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationFloor(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationGeneric(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationHosting(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationMetro(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationRack(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    facility_id: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationRegion(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationSuite(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    facility_id: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkDhcpOption(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkDhcpServer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkManagementServer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkNTPServer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkNameServer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationCustomer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationGeneric(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationManufacturer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationProvider(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityAddressGroup(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityFQDN(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityGenericAddress(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityGenericAddressGroup(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityGenericService(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityGenericServiceGroup(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityIPProtocol(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    protocol: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityIPRange(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityIpamIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityIpamPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityPolicy(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityPolicyAssignment(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityPolicyRule(LineageSource, CoreProfile, CoreNode):
    action: StringOptional
    log: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityRenderedPolicyRule(LineageSource, CoreProfile, CoreNode):
    action: StringOptional
    log: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityService(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityServiceGroup(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityServiceRange(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileSecurityZone(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceAutonomousSystem(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceBGPCommunity(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceBGPPeerGroup(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    send_community: BooleanOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceBGPSession(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    local_pref: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceGeneric(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceNetworkSegment(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceOSPF(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    reference_bandwidth: IntegerOptional
    version: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceOSPFArea(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceOSPFInterface(LineageSource, CoreProfile, CoreNode):
    authentication_key: StringOptional
    authentication_mode: DropdownOptional
    description: StringOptional
    metric: IntegerOptional
    mode: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceRoutingPolicy(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceRoutingPolicyBGP(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceRoutingPolicyOSPF(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyBranchOffice(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    emulation: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyColocationCenter(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    emulation: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyDataCenter(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    emulation: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyDeployment(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    emulation: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimConsoleInterface(
    LineageSource,
    CoreObjectComponentTemplate,
    TemplateDcimInterface,
    TemplateDcimEndpoint,
    TemplateCoreArtifactTarget,
    CoreNode,
):
    description: StringOptional
    name: String
    port: IntegerOptional
    role: DropdownOptional
    speed: IntegerOptional
    status: DropdownOptional
    template_name: String
    artifacts: RelationshipManager
    connector: RelatedNode
    device: RelatedNode
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    service: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimPhysicalDevice(
    LineageSource,
    TemplateCoreArtifactTarget,
    TemplateDcimGenericDevice,
    CoreObjectTemplate,
    CoreNode,
):
    description: StringOptional
    os_version: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    status: DropdownOptional
    template_name: String
    artifacts: RelationshipManager
    device_service: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    topology: RelatedNode


class TemplateDcimPhysicalInterface(
    LineageSource,
    CoreObjectComponentTemplate,
    TemplateDcimInterface,
    TemplateDcimEndpoint,
    TemplateDcimSubInterface,
    CoreNode,
):
    description: StringOptional
    interface_type: DropdownOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    template_name: String
    connector: RelatedNode
    device: RelatedNode
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    plugged_sfp: RelatedNode
    related_nodes: RelationshipManager
    service: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimVirtualDevice(
    LineageSource,
    TemplateCoreArtifactTarget,
    TemplateDcimGenericDevice,
    CoreObjectTemplate,
    CoreNode,
):
    description: StringOptional
    os_version: StringOptional
    role: DropdownOptional
    status: DropdownOptional
    template_name: String
    artifacts: RelationshipManager
    device_service: RelationshipManager
    hosting_device: RelatedNode
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    topology: RelatedNode


class TemplateDcimVirtualInterface(LineageSource, CoreObjectComponentTemplate, TemplateDcimInterface, CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    template_name: String
    device: RelatedNode
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    parent_interface: RelatedNode
    related_nodes: RelationshipManager
    service: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
